"use client";

import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import Image from "next/image";
import type { MembershipStatus, SampleRequest, SampleStatus, TapUser } from "../../lib/models";
import { SAMPLE_STATUS_TRANSITIONS } from "../../lib/sample-status";
import type { AuditEvent } from "../../lib/audit";
import CatalogCms from "./CatalogCms";

type Campaign = { id:string; brand:string; category:string; creatorCommission:number; delta:number; variants:number; hasSample:boolean; campaign?:string };
type View = "overview"|"creators"|"campaigns"|"samples"|"audit"|"intel";

const statusLabels:Record<SampleStatus,string>={submitted:"Pending",review:"In Process",approved:"Approved",rejected:"Reject",on_hold:"On Hold",shipped:"Shipped",received:"Received",content_submitted:"Content Submitted"};
const nextStatuses=SAMPLE_STATUS_TRANSITIONS;
const verificationLabels:Record<string,string>={code:"Kode",google:"Google",migrated:"Migrasi",grandfathered:"Sebelum verifikasi",pending:"Menunggu"};
const verificationTitles:Record<string,string>={code:"Memasukkan kode sekali pakai dari email.",google:"Email dijamin oleh Google sign-in.",migrated:"Akun lama, ditandai lewat backfill migrasi.",grandfathered:"Dibuat saat provider email belum aktif; belum pernah membuktikan email.",pending:"Registrasi belum menyelesaikan verifikasi."};
const titles:Record<View,string>={overview:"Overview KPI Afiliasi",creators:"Database Kreator",campaigns:"Katalog Campaign",samples:"Request Sample",audit:"Audit Operasional",intel:"Product Intelligence"};

function tier(followers=0){if(followers>=1_000_000)return"MEGA";if(followers>=100_000)return"MACRO";if(followers>=50_000)return"MID-TIER";if(followers>=10_000)return"MICRO";return"NANO"}
function compact(value=0){return new Intl.NumberFormat("id-ID",{notation:"compact",maximumFractionDigits:1}).format(value)}
function date(value:string){return new Intl.DateTimeFormat("id-ID",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(value))}

export default function AdminClient({adminName,logoutAction}:{adminName:string;logoutAction:()=>Promise<void>}){
 const[view,setView]=useState<View>("overview");
 const[loading,setLoading]=useState(true);
 const loadingRef=useRef(false);
 const[campaigns,setCampaigns]=useState<Campaign[]>([]);
 const[users,setUsers]=useState<TapUser[]>([]);
 const[requests,setRequests]=useState<SampleRequest[]>([]);
 const[attributedClicks,setAttributedClicks]=useState(0);
 const[retainedClicks,setRetainedClicks]=useState(0);
 const[retentionDays,setRetentionDays]=useState(180);
 const[cleanupRun,setCleanupRun]=useState<{status:string;finishedAt:string;removed?:number;error?:string;stale?:boolean}|null>(null);
 const[unprovenAdmins,setUnprovenAdmins]=useState<Array<{id:string;email:string;verificationSource:string|null}>>([]);
 const[query,setQuery]=useState("");
 const[statusFilter,setStatusFilter]=useState("all");
 const[picFilter,setPicFilter]=useState("all");
 const[yearFilter,setYearFilter]=useState("all");
 const[selectedCreator,setSelectedCreator]=useState("");
 const[selectedBrands,setSelectedBrands]=useState<string[]>([]);
 const[notice,setNotice]=useState("");
 const[success,setSuccess]=useState("");
 const[busy,setBusy]=useState(false);
 const[catalogQuality,setCatalogQuality]=useState({cells:0,brands:0,excluded:0});
 const[audits,setAudits]=useState<AuditEvent[]>([]);
 const[userPage,setUserPage]=useState(1);
 const[userTotal,setUserTotal]=useState(0);
 const[requestPage,setRequestPage]=useState(1);
 const[requestTotal,setRequestTotal]=useState(0);

 function applyCatalog(c:{campaigns?:Campaign[];meta?:{excludedInvalidRates?:number;excludedInvalidBrands?:number;excludedCampaigns?:number}}){setCampaigns(c.campaigns??[]);setCatalogQuality({cells:c.meta?.excludedInvalidRates??0,brands:c.meta?.excludedInvalidBrands??0,excluded:c.meta?.excludedCampaigns??0})}
 async function loadUsers(page=userPage,search=view==="creators"?query:""){const params=new URLSearchParams({page:String(page),limit:"50"});if(search)params.set("q",search);const payload=await fetch(`/api/admin/users?${params}`).then(r=>r.json());setUsers(payload.users??[]);setUserTotal(payload.pagination?.total??0);setUserPage(payload.pagination?.page??page)}
 async function loadRequests(page=requestPage){const params=new URLSearchParams({page:String(page),limit:"50"});if(view==="overview"){if(query)params.set("q",query);if(statusFilter!=="all")params.set("status",statusFilter);if(picFilter!=="all")params.set("pic",picFilter);if(yearFilter!=="all")params.set("year",yearFilter)}const payload=await fetch(`/api/admin/sample-requests?${params}`).then(r=>r.json());setRequests(payload.requests??[]);setRequestTotal(payload.pagination?.total??0);setRequestPage(payload.pagination?.page??page)}
 // Ref, bukan state `loading`: `loading` sengaja bernilai true sejak render
 // pertama supaya "Memuat…" langsung tampil, jadi ref inilah yang benar-benar
 // menandai sebuah fetch sedang berjalan. Menjaga terhadap panggilan
 // bertumpuk — klik "Audit Log" tepat setelah mount bisa memicu load() kedua
 // sebelum yang pertama selesai, dan tulisan state dari respons yang lebih
 // dulu terkirim bisa menimpa yang lebih baru.
 async function load(){if(loadingRef.current)return;loadingRef.current=true;setNotice("");setLoading(true);try{const[c,m,a]=await Promise.all([fetch("/api/campaigns").then(r=>r.json()),fetch("/api/admin/metrics").then(r=>r.json()),fetch("/api/admin/audits").then(r=>r.json()),loadUsers(),loadRequests()]);applyCatalog(c);setAttributedClicks(m.total??0);setRetainedClicks(m.retained??0);setRetentionDays(m.retentionDays??180);setAudits(a.events??[]);setCleanupRun(a.cron?.cleanupUsers??null);setUnprovenAdmins(a.unprovenAdmins??[])}catch{setNotice("Data operasional gagal dimuat.")}finally{loadingRef.current=false;setLoading(false)}}
 useEffect(()=>{const timer=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timer)},[]);// eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{if(view!=="creators")return;const timer=window.setTimeout(()=>{void loadUsers(1,query)},250);return()=>window.clearTimeout(timer)},[view,query]);// eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{if(view!=="overview")return;const timer=window.setTimeout(()=>{void loadRequests(1)},250);return()=>window.clearTimeout(timer)},[view,query,statusFilter,picFilter,yearFilter]);// eslint-disable-line react-hooks/exhaustive-deps

 const creators=useMemo(()=>users.filter(user=>user.role==="creator"),[users]);
 const pics=useMemo(()=>[...new Set(requests.map(item=>item.picName).filter(Boolean) as string[])].sort(),[requests]);
 const years=useMemo(()=>[...new Set(requests.map(item=>new Date(item.createdAt).getFullYear()))].sort((a,b)=>b-a),[requests]);
 const filteredRequests=useMemo(()=>requests.filter(item=>{
   const haystack=`${item.brand} ${item.username} ${item.picName??""} ${statusLabels[item.status]} ${item.trackingNumber??""}`.toLowerCase();
   return haystack.includes(query.toLowerCase())&&(statusFilter==="all"||item.status===statusFilter)&&(picFilter==="all"||item.picName===picFilter)&&(yearFilter==="all"||String(new Date(item.createdAt).getFullYear())===yearFilter);
 }),[requests,query,statusFilter,picFilter,yearFilter]);
 const selectedUser=users.find(user=>user.id===selectedCreator);
 const topPics=useMemo(()=>Object.entries(requests.reduce<Record<string,number>>((all,item)=>{if(item.picName)all[item.picName]=(all[item.picName]??0)+1;return all},{})).sort((a,b)=>b[1]-a[1]).slice(0,6),[requests]);
 const tierCounts=useMemo(()=>creators.reduce<Record<string,number>>((all,user)=>{const name=tier(user.followers);all[name]=(all[name]??0)+1;return all},{}),[creators]);

 async function membership(userId:string,membershipStatus:MembershipStatus){const response=await fetch("/api/admin/users",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({userId,membership:membershipStatus})});if(response.ok)setUsers(current=>current.map(user=>user.id===userId?{...user,membership:membershipStatus}:user));else setNotice("Status creator gagal diperbarui.")}
 async function updateRequest(item:SampleRequest,status:SampleStatus,form:HTMLFormElement){setNotice("");const values=Object.fromEntries(new FormData(form));const response=await fetch("/api/admin/sample-requests",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:item.id,status,trackingNumber:values.trackingNumber,adminNote:values.adminNote,picName:values.picName,picPhone:values.picPhone})});const payload=await response.json();if(response.ok){setRequests(current=>current.map(request=>request.id===item.id?payload.request:request));setSuccess(`${item.id} diperbarui.`)}else setNotice(payload.error??"Request gagal diperbarui.")}
 async function createRequests(event:FormEvent<HTMLFormElement>){event.preventDefault();setNotice("");setSuccess("");if(!selectedUser||!selectedBrands.length){setNotice("Pilih creator dan minimal satu brand.");return}setBusy(true);const values=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/admin/sample-requests",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...values,userId:selectedUser.id,brands:selectedBrands,username:values.username||selectedUser.tiktokUsername,recipientName:values.recipientName||selectedUser.recipientName||selectedUser.name,phone:values.phone||selectedUser.phone,address:values.address||selectedUser.address,followers:selectedUser.followers,gmv:selectedUser.gmv})});const payload=await response.json();if(response.ok){setRequests(current=>[...payload.requests,...current]);setSuccess(`${payload.requests.length} request berhasil dibuat.`);setSelectedBrands([])}else setNotice(payload.error??"Request gagal dibuat.");setBusy(false)}

 return <main className="admin-app"><aside className="admin-sidebar"><Link className="brand" href="/"><Image src="/haluan-logo.png" alt="Haluan Digital Network" width={107} height={35}/><span className="brand-divider"/><strong>TAP</strong></Link><span className="sidebar-label">ADMIN WORKSPACE</span>{([['overview','▦','Overview'],['creators','◎','Database Kreator'],['campaigns','⌁','Katalog Campaign'],['samples','+','Request Sample'],['audit','◆','Audit Log'],['intel','✦','Product Intel']] as const).map(([id,icon,label])=><button key={id} className={view===id?'active':''} aria-current={view===id?'true':undefined} onClick={()=>{setView(id);setQuery("");if(id==="audit")void load()}}><i>{icon}</i>{label}</button>)}<div className="admin-secure"><i>◆</i><b>Protected workspace</b><p>Data creator hanya tersedia untuk administrator terverifikasi.</p></div></aside>
 <section className="admin-main"><header className="admin-header"><div><span>HALUAN AFFILIATE OPERATIONS</span><h1>{titles[view]}</h1></div><div className="admin-profile"><Link href="/dashboard">← Dashboard creator</Link><span><b>{adminName}</b><small>Administrator terverifikasi</small></span><i>{adminName.slice(0,1).toUpperCase()}</i><form action={logoutAction}><button type="submit">Keluar</button></form></div></header>{loading&&<p className="admin-loading" role="status">Memuat data operasional…</p>}{unprovenAdmins.length>0&&<div className="admin-data-warning" role="status"><div><b>Admin tanpa bukti kepemilikan email</b><span>{unprovenAdmins.map(admin=>`${admin.email} (${admin.verificationSource??"belum ada"})`).join(", ")} — minta mereka melakukan reset kata sandi agar sumber verifikasi menjadi kode.</span></div><code>{unprovenAdmins.length} akun</code></div>}{catalogQuality.cells>0&&<div className="admin-data-warning" role="status"><div><b>Data rate perlu dirapikan</b><span>{catalogQuality.cells} sel pada {catalogQuality.brands} brand bermasalah; {catalogQuality.excluded} brand tidak tayang.</span></div><code>npm run audit:rates</code></div>}{notice&&<p className="admin-notice" role="alert">{notice}</p>}{success&&<p className="admin-success" role="status">{success}</p>}

 {view==="overview"&&<><div className="admin-stats hda-kpis"><article><span>TOTAL REQUEST</span><strong>{requestTotal}</strong><small>dari seluruh periode</small></article><article><span>APPROVED</span><strong>{requests.filter(r=>["approved","shipped","received","content_submitted"].includes(r.status)).length}</strong><small>di halaman ini</small></article><article><span>ADA NOMOR RESI</span><strong>{requests.filter(r=>r.trackingNumber).length}</strong><small>di halaman ini</small></article><article><span>REJECT</span><strong>{requests.filter(r=>r.status==="rejected").length}</strong><small>di halaman ini</small></article><article><span>ATTRIBUTED OPENS</span><strong>{attributedClicks}</strong><small>sejak awal · {retainedClicks} event tersimpan {retentionDays} hari</small></article></div>
 <div className="admin-overview-panels"><section className="admin-panel"><span>STATUS REQUEST</span>{(["approved","submitted","review","shipped","received","rejected","on_hold"] as SampleStatus[]).map(status=><div className="metric-line" key={status}><b>{statusLabels[status]}</b><i><em style={{width:`${requests.length?requests.filter(r=>r.status===status).length/requests.length*100:0}%`}}/></i><strong>{requests.filter(r=>r.status===status).length}</strong></div>)}</section><section className="admin-panel"><span>TIER AFFILIATOR</span>{["MEGA","MACRO","MID-TIER","MICRO","NANO"].map(name=><div className="metric-line" key={name}><b>{name}</b><i><em style={{width:`${creators.length?(tierCounts[name]??0)/creators.length*100:0}%`}}/></i><strong>{tierCounts[name]??0}</strong></div>)}</section><section className="admin-panel"><span>TOP PIC</span>{topPics.length?topPics.map(([name,count])=><div className="metric-line" key={name}><b>{name}</b><i><em style={{width:`${topPics[0]?.[1]?count/topPics[0][1]*100:0}%`}}/></i><strong>{count}</strong></div>):<p className="admin-panel-empty">Belum ada PIC pada request.</p>}</section></div>
 <section className="admin-table-panel request-log"><div className="panel-heading"><div><span>REQUEST LOG</span><h2>Data Request</h2></div><small>{requestTotal} data ditemukan</small></div><div className="admin-filterbar"><label>⌕<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Cari username, brand, PIC, status…"/></label><select aria-label="Filter status" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">Semua Status</option>{Object.entries(statusLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><select aria-label="Filter PIC" value={picFilter} onChange={e=>setPicFilter(e.target.value)}><option value="all">Semua PIC</option>{pics.map(pic=><option key={pic}>{pic}</option>)}</select><select aria-label="Filter tahun" value={yearFilter} onChange={e=>setYearFilter(e.target.value)}><option value="all">Semua Tahun</option>{years.map(year=><option key={year}>{year}</option>)}</select><button onClick={load}>⟳</button></div><div className="admin-table-wrap" role="region" aria-label="Tabel request log, bisa digeser ke samping" tabIndex={0}><table><thead><tr><th>#</th><th>Brand</th><th>Username</th><th>PIC</th><th>GMV</th><th>Status</th><th>Sample</th><th>Nomor Resi</th><th>Tanggal</th></tr></thead><tbody>{filteredRequests.map((item,index)=><tr key={item.id}><td>{(requestPage-1)*50+index+1}</td><td><b>{item.brand}</b><small>{item.id}</small></td><td><a href={item.profileUrl} target="_blank" rel="noreferrer">@{item.username}</a></td><td>{item.picName||"—"}</td><td>{item.gmv?`Rp ${compact(item.gmv)}`:"Rp 0"}</td><td><span className={`admin-status status-${item.status}`}>{statusLabels[item.status]}</span></td><td>{item.preferredSample||"—"}</td><td>{item.trackingNumber||"—"}</td><td>{date(item.createdAt)}</td></tr>)}</tbody></table></div><div className="admin-pagination"><button disabled={requestPage<=1} onClick={()=>void loadRequests(requestPage-1)}>← Sebelumnya</button><span>Halaman {requestPage} dari {Math.max(1,Math.ceil(requestTotal/50))}</span><button disabled={requestPage>=Math.ceil(requestTotal/50)} onClick={()=>void loadRequests(requestPage+1)}>Berikutnya →</button></div></section></>}{/* eslint-disable-line jsx-a11y/no-noninteractive-tabindex -- pola region bisa-geser WAI-ARIA APG: tabIndex membuatnya terjangkau keyboard, persis yang dicek axe scrollable-region-focusable */}

 {view==="creators"&&<section className="admin-table-panel"><div className="panel-heading"><div><span>DATABASE KREATOR</span><h2>{userTotal} kreator</h2></div><button onClick={load}>⟳ Refresh</button></div><div className="admin-filterbar single"><label>⌕<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Cari username, penerima, PIC…"/></label></div><div className="admin-table-wrap" role="region" aria-label="Tabel database kreator, bisa digeser ke samping" tabIndex={0}><table><thead><tr><th>Username</th><th>Tier</th><th>Followers</th><th>GMV</th><th>Penerima</th><th>Alamat</th><th>No HP</th><th>PIC</th><th>Verifikasi</th><th>Membership</th><th>Aksi</th></tr></thead><tbody>{creators.map(user=><tr key={user.id}><td><b>{user.tiktokUsername?`@${user.tiktokUsername}`:user.name}</b><small>{user.email}</small></td><td><span className="tier-pill">{tier(user.followers)}</span></td><td>{compact(user.followers)}</td><td>{user.gmv?`Rp ${compact(user.gmv)}`:"Rp 0"}</td><td>{user.recipientName||"—"}</td><td className="address-cell">{user.address||"—"}</td><td>{user.phone||"—"}</td><td>{user.assignedPic||"—"}</td><td><span className={`verification-pill verification-${user.verificationSource??"pending"}`} title={verificationTitles[user.verificationSource??"pending"]}>{verificationLabels[user.verificationSource??"pending"]}</span></td><td><span className={`membership-${user.membership}`}>{user.membership}</span></td><td><div className="row-actions"><button onClick={()=>membership(user.id,"verified")}>Verify</button><button onClick={()=>membership(user.id,"rejected")}>Reject</button></div></td></tr>)}</tbody></table></div><div className="admin-pagination"><button disabled={userPage<=1} onClick={()=>void loadUsers(userPage-1)}>← Sebelumnya</button><span>Halaman {userPage} dari {Math.max(1,Math.ceil(userTotal/50))}</span><button disabled={userPage>=Math.ceil(userTotal/50)} onClick={()=>void loadUsers(userPage+1)}>Berikutnya →</button></div></section>}{/* eslint-disable-line jsx-a11y/no-noninteractive-tabindex -- pola region bisa-geser WAI-ARIA APG: tabIndex membuatnya terjangkau keyboard, persis yang dicek axe scrollable-region-focusable */}

 {view==="campaigns"&&<CatalogCms/>}

 {view==="samples"&&<div className="sample-admin-layout"><section className="admin-panel admin-request-form"><div className="panel-heading"><div><span>FORM REQUEST SAMPLE</span><h2>Request atas nama creator</h2></div><small>Multi-brand</small></div><form onSubmit={createRequests}><label><span>Creator</span><select value={selectedCreator} onChange={event=>setSelectedCreator(event.target.value)} required><option value="">— Pilih creator —</option>{creators.map(user=><option key={user.id} value={user.id}>{user.tiktokUsername?`@${user.tiktokUsername}`:user.name}</option>)}</select></label><div className="two-col"><label><span>Username TikTok</span><input name="username" key={`${selectedCreator}-username`} defaultValue={selectedUser?.tiktokUsername||""} placeholder="tanpa @"/></label><label><span>SOW</span><select name="sow"><option value="">— Pilih —</option><option>VT</option><option>Live</option><option>Live + VT</option></select></label></div><div className="two-col"><label><span>Nama penerima</span><input name="recipientName" key={`${selectedCreator}-recipient`} defaultValue={selectedUser?.recipientName||selectedUser?.name||""}/></label><label><span>No HP / WA</span><input name="phone" key={`${selectedCreator}-phone`} defaultValue={selectedUser?.phone||""}/></label></div><label><span>Alamat lengkap</span><textarea name="address" key={`${selectedCreator}-address`} defaultValue={selectedUser?.address||""} rows={3}/></label><div className="two-col"><label><span>PIC Haluan</span><input name="picName" defaultValue={selectedUser?.assignedPic||""} placeholder="Nama PIC"/></label><label><span>No HP PIC</span><input name="picPhone" placeholder="08xx…"/></label></div><label><span>Prefer sample</span><input name="preferredSample" placeholder="Nama produk"/></label><fieldset><legend>Brand tujuan <b>{selectedBrands.length} dipilih</b></legend><div className="brand-checklist">{campaigns.filter(campaign=>campaign.hasSample).map(campaign=><label key={campaign.id}><input type="checkbox" checked={selectedBrands.includes(campaign.brand)} onChange={event=>setSelectedBrands(current=>event.target.checked?[...current,campaign.brand]:current.filter(brand=>brand!==campaign.brand))}/><span>{campaign.brand}</span></label>)}</div></fieldset><button className="admin-primary" type="submit" disabled={busy}>{busy?"Menyimpan…":`Kirim ${selectedBrands.length||""} request`}</button></form></section>
 <section className="admin-table-panel admin-lifecycle"><div className="panel-heading"><div><span>REQUEST LIFECYCLE</span><h2>{requestTotal} request sample</h2></div></div>{requests.map(item=><form className="request-editor" key={item.id} onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const selected=form.elements.namedItem("status") as HTMLSelectElement;updateRequest(item,selected.value as SampleStatus,form)}}><div><b>{item.brand}</b><small>@{item.username} · {item.id}</small></div><input name="picName" defaultValue={item.picName||""} placeholder="PIC" aria-label={`PIC ${item.id}`}/><input name="picPhone" defaultValue={item.picPhone||""} placeholder="No HP PIC" aria-label={`No HP PIC ${item.id}`}/><input name="trackingNumber" defaultValue={item.trackingNumber||""} placeholder="Nomor resi" aria-label={`Nomor resi ${item.id}`}/><input name="adminNote" defaultValue={item.adminNote||""} placeholder="Catatan" aria-label={`Catatan ${item.id}`}/><select name="status" value={item.status} aria-label={`Status ${item.id}`} onChange={event=>updateRequest(item,event.target.value as SampleStatus,event.currentTarget.form!)}><option value={item.status}>{statusLabels[item.status]}</option>{nextStatuses[item.status].map(status=><option key={status} value={status}>{statusLabels[status]}</option>)}</select><button>Simpan</button></form>)}<div className="admin-pagination"><button disabled={requestPage<=1} onClick={()=>void loadRequests(requestPage-1)}>← Sebelumnya</button><span>Halaman {requestPage} dari {Math.max(1,Math.ceil(requestTotal/50))}</span><button disabled={requestPage>=Math.ceil(requestTotal/50)} onClick={()=>void loadRequests(requestPage+1)}>Berikutnya →</button></div></section></div>}

 {view==="intel"&&<section className="admin-intel"><div className="admin-intel-hero"><span>WEEKLY RECOMMENDATION ENGINE</span><h2>Product of the Week,<br/>dipilih dengan data.</h2><p>Kandidat dinilai dari momentum produk, creator aktif, saturasi konten, extra rate TAP, kesiapan sample, dan conversion first-party.</p><div><b>FastMoss API</b><b>Kalodata research</b><b>TAP attribution</b></div></div><div className="intel-formula"><span>RECOMMENDATION SCORE</span>{[["Sales velocity","30%"],["Creator growth","20%"],["Low saturation","15%"],["Extra commission","20%"],["Sample readiness","15%"]].map(([label,weight])=><p key={label}><b>{label}</b><strong>{weight}</strong></p>)}<small>Pemenang tidak dipublikasikan sebelum connector dan timestamp verifikasi tersedia.</small></div></section>}
 {view==="audit"&&<section className="admin-table-panel"><div className="panel-heading"><div><span>READ-ONLY AUDIT TRAIL</span><h2>{audits.length} aktivitas terbaru</h2><small className={`audit-cron-note${cleanupRun&&(cleanupRun.stale||cleanupRun.status!=="succeeded")?" audit-cron-warn":""}`}>Pembersihan akun pending: {cleanupRun?`${cleanupRun.status==="succeeded"?"berhasil":`gagal (${cleanupRun.error??"tidak diketahui"})`} pada ${date(cleanupRun.finishedAt)} · ${cleanupRun.removed??0} akun dihapus${cleanupRun.stale?" · lebih dari 26 jam lalu":""}`:"belum pernah tercatat — periksa CRON_SECRET di Vercel"}</small></div><button onClick={load}>⟳ Refresh</button></div><div className="admin-filterbar single"><label>⌕<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Cari aktor, aksi, atau target…"/></label></div><div className="admin-table-wrap" role="region" aria-label="Tabel audit trail, bisa digeser ke samping" tabIndex={0}><table><thead><tr><th>Waktu</th><th>Aktor</th><th>Aksi</th><th>Target</th><th>Sebelum</th><th>Sesudah</th></tr></thead><tbody>{audits.filter(event=>`${event.actorId} ${event.action} ${event.targetId}`.toLowerCase().includes(query.toLowerCase())).map(event=><tr key={event.id}><td>{date(event.createdAt)}</td><td><code>{event.actorId}</code></td><td><b>{event.action}</b></td><td><code>{event.targetId}</code></td><td><pre>{JSON.stringify(event.before??null,null,2)}</pre></td><td><pre>{JSON.stringify(event.after??null,null,2)}</pre></td></tr>)}</tbody></table></div></section>}{/* eslint-disable-line jsx-a11y/no-noninteractive-tabindex -- pola region bisa-geser WAI-ARIA APG: tabIndex membuatnya terjangkau keyboard, persis yang dicek axe scrollable-region-focusable */}
 </section></main>
}
